backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "static/img" # Folder where user uploaded files should go
public_folder: "/img" # Folder path where uploaded files will be accessed

collections: # A list of collections the CMS should be able to edit
  - name: "blog" # Used in routes, ie.: /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/pages/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
